/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Auction {
      
    export type AuctionItemStruct = {id: BigNumberish, seller: AddressLike, nft: AddressLike, tokenId: BigNumberish, startPrice: BigNumberish, endTime: BigNumberish, highestBidder: AddressLike, highestBid: BigNumberish, settled: boolean}

    export type AuctionItemStructOutput = [id: bigint, seller: string, nft: string, tokenId: bigint, startPrice: bigint, endTime: bigint, highestBidder: string, highestBid: bigint, settled: boolean] & {id: bigint, seller: string, nft: string, tokenId: bigint, startPrice: bigint, endTime: bigint, highestBidder: string, highestBid: bigint, settled: boolean }
  
    }

  export interface AuctionInterface extends Interface {
    getFunction(nameOrSignature: "auctions" | "bid" | "createAuction" | "endAuction" | "getActiveAuctions" | "nextAuctionId" | "onERC721Received" | "paymentToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionCreated" | "AuctionEnded" | "NewBid"): EventFragment;

    encodeFunctionData(functionFragment: 'auctions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'bid', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createAuction', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'endAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getActiveAuctions', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextAuctionId', values?: undefined): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'paymentToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'auctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActiveAuctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextAuctionId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentToken', data: BytesLike): Result;
  }

  
    export namespace AuctionCreatedEvent {
      export type InputTuple = [id: BigNumberish, seller: AddressLike, nft: AddressLike, tokenId: BigNumberish, startPrice: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [id: bigint, seller: string, nft: string, tokenId: bigint, startPrice: bigint, endTime: bigint];
      export interface OutputObject {id: bigint, seller: string, nft: string, tokenId: bigint, startPrice: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionEndedEvent {
      export type InputTuple = [id: BigNumberish, winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [id: bigint, winner: string, amount: bigint];
      export interface OutputObject {id: bigint, winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NewBidEvent {
      export type InputTuple = [id: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [id: bigint, bidder: string, amount: bigint];
      export interface OutputObject {id: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Auction extends BaseContract {
    
    connect(runner?: ContractRunner | null): Auction;
    waitForDeployment(): Promise<this>;

    interface: AuctionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    auctions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, string, bigint, boolean] & {id: bigint, seller: string, nft: string, tokenId: bigint, startPrice: bigint, endTime: bigint, highestBidder: string, highestBid: bigint, settled: boolean }],
      'view'
    >
    

    
    bid: TypedContractMethod<
      [id: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createAuction: TypedContractMethod<
      [nft: AddressLike, tokenId: BigNumberish, startPrice: BigNumberish, durationSeconds: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    endAuction: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getActiveAuctions: TypedContractMethod<
      [],
      [Auction.AuctionItemStructOutput[]],
      'view'
    >
    

    
    nextAuctionId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    onERC721Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'view'
    >
    

    
    paymentToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'auctions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, string, bigint, boolean] & {id: bigint, seller: string, nft: string, tokenId: bigint, startPrice: bigint, endTime: bigint, highestBidder: string, highestBid: bigint, settled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'bid'): TypedContractMethod<
      [id: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createAuction'): TypedContractMethod<
      [nft: AddressLike, tokenId: BigNumberish, startPrice: BigNumberish, durationSeconds: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endAuction'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getActiveAuctions'): TypedContractMethod<
      [],
      [Auction.AuctionItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'nextAuctionId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paymentToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AuctionCreated'): TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
getEvent(key: 'AuctionEnded'): TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
getEvent(key: 'NewBid'): TypedContractEvent<NewBidEvent.InputTuple, NewBidEvent.OutputTuple, NewBidEvent.OutputObject>;

    filters: {
      
      'AuctionCreated(uint256,address,address,uint256,uint256,uint256)': TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
      AuctionCreated: TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
    

      'AuctionEnded(uint256,address,uint256)': TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
      AuctionEnded: TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
    

      'NewBid(uint256,address,uint256)': TypedContractEvent<NewBidEvent.InputTuple, NewBidEvent.OutputTuple, NewBidEvent.OutputObject>;
      NewBid: TypedContractEvent<NewBidEvent.InputTuple, NewBidEvent.OutputTuple, NewBidEvent.OutputObject>;
    
    };
  }