/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'MallToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MallToken__factory>
getContractFactory(name: 'Auction', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Auction__factory>
getContractFactory(name: 'MallItem', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MallItem__factory>
getContractFactory(name: 'PriceConsumer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PriceConsumer__factory>
getContractFactory(name: 'Marketplace', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Marketplace__factory>

  getContractAt(name: 'MallToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MallToken>
getContractAt(name: 'Auction', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Auction>
getContractAt(name: 'MallItem', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MallItem>
getContractAt(name: 'PriceConsumer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PriceConsumer>
getContractAt(name: 'Marketplace', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Marketplace>

  deployContract(name: 'MallToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MallToken>
deployContract(name: 'Auction', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Auction>
deployContract(name: 'MallItem', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MallItem>
deployContract(name: 'PriceConsumer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PriceConsumer>
deployContract(name: 'Marketplace', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Marketplace>

  deployContract(name: 'MallToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MallToken>
deployContract(name: 'Auction', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Auction>
deployContract(name: 'MallItem', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MallItem>
deployContract(name: 'PriceConsumer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PriceConsumer>
deployContract(name: 'Marketplace', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Marketplace>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  