/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Marketplace {
      
    export type ListingStruct = {listingId: BigNumberish, seller: AddressLike, nft: AddressLike, tokenId: BigNumberish, price: BigNumberish, active: boolean}

    export type ListingStructOutput = [listingId: bigint, seller: string, nft: string, tokenId: bigint, price: bigint, active: boolean] & {listingId: bigint, seller: string, nft: string, tokenId: bigint, price: bigint, active: boolean }
  
    }

  export interface MarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "buy" | "cancel" | "getActiveListings" | "list" | "listings" | "nextListingId" | "onERC721Received" | "paymentToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Cancelled" | "Listed" | "Purchased"): EventFragment;

    encodeFunctionData(functionFragment: 'buy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getActiveListings', values?: undefined): string;
encodeFunctionData(functionFragment: 'list', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'listings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextListingId', values?: undefined): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'paymentToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActiveListings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'list', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextListingId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentToken', data: BytesLike): Result;
  }

  
    export namespace CancelledEvent {
      export type InputTuple = [listingId: BigNumberish];
      export type OutputTuple = [listingId: bigint];
      export interface OutputObject {listingId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListedEvent {
      export type InputTuple = [listingId: BigNumberish, seller: AddressLike, nft: AddressLike, tokenId: BigNumberish, price: BigNumberish];
      export type OutputTuple = [listingId: bigint, seller: string, nft: string, tokenId: bigint, price: bigint];
      export interface OutputObject {listingId: bigint, seller: string, nft: string, tokenId: bigint, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PurchasedEvent {
      export type InputTuple = [listingId: BigNumberish, buyer: AddressLike, seller: AddressLike, price: BigNumberish];
      export type OutputTuple = [listingId: bigint, buyer: string, seller: string, price: bigint];
      export interface OutputObject {listingId: bigint, buyer: string, seller: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Marketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): Marketplace;
    waitForDeployment(): Promise<this>;

    interface: MarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buy: TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancel: TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getActiveListings: TypedContractMethod<
      [],
      [Marketplace.ListingStructOutput[]],
      'view'
    >
    

    
    list: TypedContractMethod<
      [nft: AddressLike, tokenId: BigNumberish, price: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    listings: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, boolean] & {listingId: bigint, seller: string, nft: string, tokenId: bigint, price: bigint, active: boolean }],
      'view'
    >
    

    
    nextListingId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    onERC721Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'view'
    >
    

    
    paymentToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancel'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getActiveListings'): TypedContractMethod<
      [],
      [Marketplace.ListingStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'list'): TypedContractMethod<
      [nft: AddressLike, tokenId: BigNumberish, price: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listings'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, boolean] & {listingId: bigint, seller: string, nft: string, tokenId: bigint, price: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'nextListingId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paymentToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Cancelled'): TypedContractEvent<CancelledEvent.InputTuple, CancelledEvent.OutputTuple, CancelledEvent.OutputObject>;
getEvent(key: 'Listed'): TypedContractEvent<ListedEvent.InputTuple, ListedEvent.OutputTuple, ListedEvent.OutputObject>;
getEvent(key: 'Purchased'): TypedContractEvent<PurchasedEvent.InputTuple, PurchasedEvent.OutputTuple, PurchasedEvent.OutputObject>;

    filters: {
      
      'Cancelled(uint256)': TypedContractEvent<CancelledEvent.InputTuple, CancelledEvent.OutputTuple, CancelledEvent.OutputObject>;
      Cancelled: TypedContractEvent<CancelledEvent.InputTuple, CancelledEvent.OutputTuple, CancelledEvent.OutputObject>;
    

      'Listed(uint256,address,address,uint256,uint256)': TypedContractEvent<ListedEvent.InputTuple, ListedEvent.OutputTuple, ListedEvent.OutputObject>;
      Listed: TypedContractEvent<ListedEvent.InputTuple, ListedEvent.OutputTuple, ListedEvent.OutputObject>;
    

      'Purchased(uint256,address,address,uint256)': TypedContractEvent<PurchasedEvent.InputTuple, PurchasedEvent.OutputTuple, PurchasedEvent.OutputObject>;
      Purchased: TypedContractEvent<PurchasedEvent.InputTuple, PurchasedEvent.OutputTuple, PurchasedEvent.OutputObject>;
    
    };
  }