/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { PriceConsumer, PriceConsumerInterface } from "../PriceConsumer.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "feed",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "getDecimals",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getLatestPrice",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "priceFeed",
    "outputs": [
      {
        "internalType": "contract AggregatorV3Interface",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a0604052348015600e575f5ffd5b5060405161031d38038061031d833981016040819052602b91603b565b6001600160a01b03166080526066565b5f60208284031215604a575f5ffd5b81516001600160a01b0381168114605f575f5ffd5b9392505050565b60805161029361008a5f395f818160480152818160bb015261014701526102935ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c8063741bef1a146100435780638e15f47314610087578063f0141d841461009d575b5f5ffd5b61006a7f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b0390911681526020015b60405180910390f35b61008f6100b7565b60405190815260200161007e565b6100a5610144565b60405160ff909116815260200161007e565b5f5f7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b031663feaf968c6040518163ffffffff1660e01b815260040160a060405180830381865afa158015610115573d5f5f3e3d5ffd5b505050506040513d601f19601f8201168201806040525081019061013991906101e8565b509195945050505050565b5f7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b031663313ce5676040518163ffffffff1660e01b8152600401602060405180830381865afa1580156101a1573d5f5f3e3d5ffd5b505050506040513d601f19601f820116820180604052508101906101c59190610236565b905090565b805169ffffffffffffffffffff811681146101e3575f5ffd5b919050565b5f5f5f5f5f60a086880312156101fc575f5ffd5b610205866101ca565b6020870151604088015160608901519297509095509350915061022a608087016101ca565b90509295509295909350565b5f60208284031215610246575f5ffd5b815160ff81168114610256575f5ffd5b939250505056fea2646970667358221220704e90530e6da699875b58af9ff6f12810e1957c4304ad267d22ce9fcd8c0b6d64736f6c634300081c0033";

  
      type PriceConsumerConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: PriceConsumerConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class PriceConsumer__factory extends ContractFactory {
    
      constructor(...args: PriceConsumerConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(feed: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(feed, overrides || {});
    };
    override deploy(feed: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(feed, overrides || {}) as Promise<PriceConsumer & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): PriceConsumer__factory {
      return super.connect(runner) as PriceConsumer__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): PriceConsumerInterface {
      return new Interface(_abi) as PriceConsumerInterface;
    }
    
    override attach(address: string | Addressable): PriceConsumer {
      return super.attach(address) as PriceConsumer;
    }
  static connect(address: string, runner?: ContractRunner | null): PriceConsumer {
      return new Contract(address, _abi, runner) as unknown as PriceConsumer;
    }
  }

  
  